// If you don't want to use TypeScript you can delete this file!
import React from "react"
import { PageProps, Link, graphql } from "gatsby"

import Layout from "../components/layout"
import SEO from "../components/seo"

type DataProps = {
  site: {
    buildTime: string
  }
}

const UsingTypescript: React.FC<PageProps<DataProps>> = ({ data, path }) => (
  <Layout>
    <SEO title="Using TypeScript" />
    <h1>Gatsby supports TypeScript by default!</h1>
    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce rhoncus ipsum quis leo mattis pharetra. Nunc posuere, libero et auctor aliquet, risus ligula sagittis libero, sed molestie ligula tellus id mi. Praesent feugiat interdum enim, quis laoreet metus placerat eget. In sit amet tempor nunc. Maecenas id massa gravida, porta tellus in, sodales libero. Sed id auctor lectus. Morbi lorem dui, eleifend id tellus et, blandit lobortis quam. Sed convallis tellus sed eros elementum, rhoncus tincidunt sapien vulputate. In porta molestie varius. In a lorem a nulla vehicula tempor. Sed scelerisque volutpat ante, in venenatis lectus aliquam cursus. In dictum ac arcu id feugiat. Phasellus quis eros a leo blandit ultricies. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas aliquam libero nec est sagittis ullamcorper.

Mauris blandit vehicula lorem at elementum. Nam sollicitudin eu lacus ut luctus. Quisque sed auctor risus, auctor condimentum libero. Pellentesque at efficitur eros. Proin lacinia, lacus ac porttitor suscipit, augue justo rutrum tellus, ut vehicula tortor ex iaculis diam. Duis id hendrerit ex. Ut et diam a lorem eleifend lacinia sit amet vitae odio. Pellentesque non molestie felis. Aliquam ac ornare turpis, vehicula facilisis lectus. Quisque dolor ipsum, placerat non lobortis in, varius non massa. Sed maximus euismod neque. Donec consequat, risus nec dapibus vulputate, tellus magna ultricies metus, non pulvinar justo lorem sit amet nisi. Suspendisse sollicitudin ex lectus, vitae varius quam condimentum ac. Praesent vehicula est sed dui tempus ornare. Integer egestas malesuada placerat.

Integer interdum leo sit amet eros maximus, eu consequat diam lobortis. Cras varius est et cursus viverra. Nunc aliquet fermentum libero, malesuada accumsan augue consequat id. Donec consectetur tortor id lectus gravida mattis. Nam ut dolor vitae leo tristique tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus orci in velit molestie sollicitudin. Morbi suscipit sem non fermentum malesuada. Nullam ac nisi sodales, ultrices dolor in, lacinia orci. Nam nisi lacus, suscipit sit amet varius vel, pretium et massa. Sed id massa sed ligula mollis tristique sed ac magna. Sed egestas, magna non semper ornare, velit nulla porttitor arcu, eget tempor est tortor quis lectus. Aenean dignissim in diam sed facilisis.

Integer nec risus elit. Duis tempus nunc odio, id tempor velit consectetur at. Pellentesque sed posuere metus, sit amet tincidunt felis. Maecenas vehicula viverra ipsum. Nunc arcu urna, feugiat et mattis ornare, molestie in quam. Fusce ac consequat nibh. Morbi porttitor non ligula sagittis vestibulum. Pellentesque egestas, dui ut finibus maximus, lectus neque fringilla ante, vitae laoreet nisl massa eget nisi. Cras egestas ipsum in massa mollis, sit amet suscipit velit sodales. In porttitor lectus et dui malesuada consectetur. Praesent lobortis odio eu mauris maximus iaculis. Quisque aliquet dolor id eleifend fermentum. Nullam finibus metus sagittis auctor hendrerit. Pellentesque vel erat eget nulla vehicula tempus. Duis in dictum urna.

Aliquam nibh mi, faucibus et sem nec, venenatis finibus leo. Curabitur feugiat felis at mauris bibendum, vehicula imperdiet elit sagittis. Ut feugiat gravida turpis, at euismod sapien imperdiet vitae. Sed mattis tortor eget consectetur maximus. Sed ultricies, purus eu eleifend bibendum, justo elit tristique mauris, quis mattis sem magna ut neque. Morbi euismod velit nec justo tempor lacinia. Vivamus faucibus nibh ac porttitor dapibus.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce rhoncus ipsum quis leo mattis pharetra. Nunc posuere, libero et auctor aliquet, risus ligula sagittis libero, sed molestie ligula tellus id mi. Praesent feugiat interdum enim, quis laoreet metus placerat eget. In sit amet tempor nunc. Maecenas id massa gravida, porta tellus in, sodales libero. Sed id auctor lectus. Morbi lorem dui, eleifend id tellus et, blandit lobortis quam. Sed convallis tellus sed eros elementum, rhoncus tincidunt sapien vulputate. In porta molestie varius. In a lorem a nulla vehicula tempor. Sed scelerisque volutpat ante, in venenatis lectus aliquam cursus. In dictum ac arcu id feugiat. Phasellus quis eros a leo blandit ultricies. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas aliquam libero nec est sagittis ullamcorper.

Mauris blandit vehicula lorem at elementum. Nam sollicitudin eu lacus ut luctus. Quisque sed auctor risus, auctor condimentum libero. Pellentesque at efficitur eros. Proin lacinia, lacus ac porttitor suscipit, augue justo rutrum tellus, ut vehicula tortor ex iaculis diam. Duis id hendrerit ex. Ut et diam a lorem eleifend lacinia sit amet vitae odio. Pellentesque non molestie felis. Aliquam ac ornare turpis, vehicula facilisis lectus. Quisque dolor ipsum, placerat non lobortis in, varius non massa. Sed maximus euismod neque. Donec consequat, risus nec dapibus vulputate, tellus magna ultricies metus, non pulvinar justo lorem sit amet nisi. Suspendisse sollicitudin ex lectus, vitae varius quam condimentum ac. Praesent vehicula est sed dui tempus ornare. Integer egestas malesuada placerat.

Integer interdum leo sit amet eros maximus, eu consequat diam lobortis. Cras varius est et cursus viverra. Nunc aliquet fermentum libero, malesuada accumsan augue consequat id. Donec consectetur tortor id lectus gravida mattis. Nam ut dolor vitae leo tristique tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus orci in velit molestie sollicitudin. Morbi suscipit sem non fermentum malesuada. Nullam ac nisi sodales, ultrices dolor in, lacinia orci. Nam nisi lacus, suscipit sit amet varius vel, pretium et massa. Sed id massa sed ligula mollis tristique sed ac magna. Sed egestas, magna non semper ornare, velit nulla porttitor arcu, eget tempor est tortor quis lectus. Aenean dignissim in diam sed facilisis.

Integer nec risus elit. Duis tempus nunc odio, id tempor velit consectetur at. Pellentesque sed posuere metus, sit amet tincidunt felis. Maecenas vehicula viverra ipsum. Nunc arcu urna, feugiat et mattis ornare, molestie in quam. Fusce ac consequat nibh. Morbi porttitor non ligula sagittis vestibulum. Pellentesque egestas, dui ut finibus maximus, lectus neque fringilla ante, vitae laoreet nisl massa eget nisi. Cras egestas ipsum in massa mollis, sit amet suscipit velit sodales. In porttitor lectus et dui malesuada consectetur. Praesent lobortis odio eu mauris maximus iaculis. Quisque aliquet dolor id eleifend fermentum. Nullam finibus metus sagittis auctor hendrerit. Pellentesque vel erat eget nulla vehicula tempus. Duis in dictum urna.

Aliquam nibh mi, faucibus et sem nec, venenatis finibus leo. Curabitur feugiat felis at mauris bibendum, vehicula imperdiet elit sagittis. Ut feugiat gravida turpis, at euismod sapien imperdiet vitae. Sed mattis tortor eget consectetur maximus. Sed ultricies, purus eu eleifend bibendum, justo elit tristique mauris, quis mattis sem magna ut neque. Morbi euismod velit nec justo tempor lacinia. Vivamus faucibus nibh ac porttitor dapibus.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce rhoncus ipsum quis leo mattis pharetra. Nunc posuere, libero et auctor aliquet, risus ligula sagittis libero, sed molestie ligula tellus id mi. Praesent feugiat interdum enim, quis laoreet metus placerat eget. In sit amet tempor nunc. Maecenas id massa gravida, porta tellus in, sodales libero. Sed id auctor lectus. Morbi lorem dui, eleifend id tellus et, blandit lobortis quam. Sed convallis tellus sed eros elementum, rhoncus tincidunt sapien vulputate. In porta molestie varius. In a lorem a nulla vehicula tempor. Sed scelerisque volutpat ante, in venenatis lectus aliquam cursus. In dictum ac arcu id feugiat. Phasellus quis eros a leo blandit ultricies. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas aliquam libero nec est sagittis ullamcorper.

Mauris blandit vehicula lorem at elementum. Nam sollicitudin eu lacus ut luctus. Quisque sed auctor risus, auctor condimentum libero. Pellentesque at efficitur eros. Proin lacinia, lacus ac porttitor suscipit, augue justo rutrum tellus, ut vehicula tortor ex iaculis diam. Duis id hendrerit ex. Ut et diam a lorem eleifend lacinia sit amet vitae odio. Pellentesque non molestie felis. Aliquam ac ornare turpis, vehicula facilisis lectus. Quisque dolor ipsum, placerat non lobortis in, varius non massa. Sed maximus euismod neque. Donec consequat, risus nec dapibus vulputate, tellus magna ultricies metus, non pulvinar justo lorem sit amet nisi. Suspendisse sollicitudin ex lectus, vitae varius quam condimentum ac. Praesent vehicula est sed dui tempus ornare. Integer egestas malesuada placerat.

Integer interdum leo sit amet eros maximus, eu consequat diam lobortis. Cras varius est et cursus viverra. Nunc aliquet fermentum libero, malesuada accumsan augue consequat id. Donec consectetur tortor id lectus gravida mattis. Nam ut dolor vitae leo tristique tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus orci in velit molestie sollicitudin. Morbi suscipit sem non fermentum malesuada. Nullam ac nisi sodales, ultrices dolor in, lacinia orci. Nam nisi lacus, suscipit sit amet varius vel, pretium et massa. Sed id massa sed ligula mollis tristique sed ac magna. Sed egestas, magna non semper ornare, velit nulla porttitor arcu, eget tempor est tortor quis lectus. Aenean dignissim in diam sed facilisis.

Integer nec risus elit. Duis tempus nunc odio, id tempor velit consectetur at. Pellentesque sed posuere metus, sit amet tincidunt felis. Maecenas vehicula viverra ipsum. Nunc arcu urna, feugiat et mattis ornare, molestie in quam. Fusce ac consequat nibh. Morbi porttitor non ligula sagittis vestibulum. Pellentesque egestas, dui ut finibus maximus, lectus neque fringilla ante, vitae laoreet nisl massa eget nisi. Cras egestas ipsum in massa mollis, sit amet suscipit velit sodales. In porttitor lectus et dui malesuada consectetur. Praesent lobortis odio eu mauris maximus iaculis. Quisque aliquet dolor id eleifend fermentum. Nullam finibus metus sagittis auctor hendrerit. Pellentesque vel erat eget nulla vehicula tempus. Duis in dictum urna.

Aliquam nibh mi, faucibus et sem nec, venenatis finibus leo. Curabitur feugiat felis at mauris bibendum, vehicula imperdiet elit sagittis. Ut feugiat gravida turpis, at euismod sapien imperdiet vitae. Sed mattis tortor eget consectetur maximus. Sed ultricies, purus eu eleifend bibendum, justo elit tristique mauris, quis mattis sem magna ut neque. Morbi euismod velit nec justo tempor lacinia. Vivamus faucibus nibh ac porttitor dapibus.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce rhoncus ipsum quis leo mattis pharetra. Nunc posuere, libero et auctor aliquet, risus ligula sagittis libero, sed molestie ligula tellus id mi. Praesent feugiat interdum enim, quis laoreet metus placerat eget. In sit amet tempor nunc. Maecenas id massa gravida, porta tellus in, sodales libero. Sed id auctor lectus. Morbi lorem dui, eleifend id tellus et, blandit lobortis quam. Sed convallis tellus sed eros elementum, rhoncus tincidunt sapien vulputate. In porta molestie varius. In a lorem a nulla vehicula tempor. Sed scelerisque volutpat ante, in venenatis lectus aliquam cursus. In dictum ac arcu id feugiat. Phasellus quis eros a leo blandit ultricies. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas aliquam libero nec est sagittis ullamcorper.

Mauris blandit vehicula lorem at elementum. Nam sollicitudin eu lacus ut luctus. Quisque sed auctor risus, auctor condimentum libero. Pellentesque at efficitur eros. Proin lacinia, lacus ac porttitor suscipit, augue justo rutrum tellus, ut vehicula tortor ex iaculis diam. Duis id hendrerit ex. Ut et diam a lorem eleifend lacinia sit amet vitae odio. Pellentesque non molestie felis. Aliquam ac ornare turpis, vehicula facilisis lectus. Quisque dolor ipsum, placerat non lobortis in, varius non massa. Sed maximus euismod neque. Donec consequat, risus nec dapibus vulputate, tellus magna ultricies metus, non pulvinar justo lorem sit amet nisi. Suspendisse sollicitudin ex lectus, vitae varius quam condimentum ac. Praesent vehicula est sed dui tempus ornare. Integer egestas malesuada placerat.

Integer interdum leo sit amet eros maximus, eu consequat diam lobortis. Cras varius est et cursus viverra. Nunc aliquet fermentum libero, malesuada accumsan augue consequat id. Donec consectetur tortor id lectus gravida mattis. Nam ut dolor vitae leo tristique tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus orci in velit molestie sollicitudin. Morbi suscipit sem non fermentum malesuada. Nullam ac nisi sodales, ultrices dolor in, lacinia orci. Nam nisi lacus, suscipit sit amet varius vel, pretium et massa. Sed id massa sed ligula mollis tristique sed ac magna. Sed egestas, magna non semper ornare, velit nulla porttitor arcu, eget tempor est tortor quis lectus. Aenean dignissim in diam sed facilisis.

Integer nec risus elit. Duis tempus nunc odio, id tempor velit consectetur at. Pellentesque sed posuere metus, sit amet tincidunt felis. Maecenas vehicula viverra ipsum. Nunc arcu urna, feugiat et mattis ornare, molestie in quam. Fusce ac consequat nibh. Morbi porttitor non ligula sagittis vestibulum. Pellentesque egestas, dui ut finibus maximus, lectus neque fringilla ante, vitae laoreet nisl massa eget nisi. Cras egestas ipsum in massa mollis, sit amet suscipit velit sodales. In porttitor lectus et dui malesuada consectetur. Praesent lobortis odio eu mauris maximus iaculis. Quisque aliquet dolor id eleifend fermentum. Nullam finibus metus sagittis auctor hendrerit. Pellentesque vel erat eget nulla vehicula tempus. Duis in dictum urna.

Aliquam nibh mi, faucibus et sem nec, venenatis finibus leo. Curabitur feugiat felis at mauris bibendum, vehicula imperdiet elit sagittis. Ut feugiat gravida turpis, at euismod sapien imperdiet vitae. Sed mattis tortor eget consectetur maximus. Sed ultricies, purus eu eleifend bibendum, justo elit tristique mauris, quis mattis sem magna ut neque. Morbi euismod velit nec justo tempor lacinia. Vivamus faucibus nibh ac porttitor dapibus.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce rhoncus ipsum quis leo mattis pharetra. Nunc posuere, libero et auctor aliquet, risus ligula sagittis libero, sed molestie ligula tellus id mi. Praesent feugiat interdum enim, quis laoreet metus placerat eget. In sit amet tempor nunc. Maecenas id massa gravida, porta tellus in, sodales libero. Sed id auctor lectus. Morbi lorem dui, eleifend id tellus et, blandit lobortis quam. Sed convallis tellus sed eros elementum, rhoncus tincidunt sapien vulputate. In porta molestie varius. In a lorem a nulla vehicula tempor. Sed scelerisque volutpat ante, in venenatis lectus aliquam cursus. In dictum ac arcu id feugiat. Phasellus quis eros a leo blandit ultricies. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas aliquam libero nec est sagittis ullamcorper.

Mauris blandit vehicula lorem at elementum. Nam sollicitudin eu lacus ut luctus. Quisque sed auctor risus, auctor condimentum libero. Pellentesque at efficitur eros. Proin lacinia, lacus ac porttitor suscipit, augue justo rutrum tellus, ut vehicula tortor ex iaculis diam. Duis id hendrerit ex. Ut et diam a lorem eleifend lacinia sit amet vitae odio. Pellentesque non molestie felis. Aliquam ac ornare turpis, vehicula facilisis lectus. Quisque dolor ipsum, placerat non lobortis in, varius non massa. Sed maximus euismod neque. Donec consequat, risus nec dapibus vulputate, tellus magna ultricies metus, non pulvinar justo lorem sit amet nisi. Suspendisse sollicitudin ex lectus, vitae varius quam condimentum ac. Praesent vehicula est sed dui tempus ornare. Integer egestas malesuada placerat.

Integer interdum leo sit amet eros maximus, eu consequat diam lobortis. Cras varius est et cursus viverra. Nunc aliquet fermentum libero, malesuada accumsan augue consequat id. Donec consectetur tortor id lectus gravida mattis. Nam ut dolor vitae leo tristique tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus orci in velit molestie sollicitudin. Morbi suscipit sem non fermentum malesuada. Nullam ac nisi sodales, ultrices dolor in, lacinia orci. Nam nisi lacus, suscipit sit amet varius vel, pretium et massa. Sed id massa sed ligula mollis tristique sed ac magna. Sed egestas, magna non semper ornare, velit nulla porttitor arcu, eget tempor est tortor quis lectus. Aenean dignissim in diam sed facilisis.

Integer nec risus elit. Duis tempus nunc odio, id tempor velit consectetur at. Pellentesque sed posuere metus, sit amet tincidunt felis. Maecenas vehicula viverra ipsum. Nunc arcu urna, feugiat et mattis ornare, molestie in quam. Fusce ac consequat nibh. Morbi porttitor non ligula sagittis vestibulum. Pellentesque egestas, dui ut finibus maximus, lectus neque fringilla ante, vitae laoreet nisl massa eget nisi. Cras egestas ipsum in massa mollis, sit amet suscipit velit sodales. In porttitor lectus et dui malesuada consectetur. Praesent lobortis odio eu mauris maximus iaculis. Quisque aliquet dolor id eleifend fermentum. Nullam finibus metus sagittis auctor hendrerit. Pellentesque vel erat eget nulla vehicula tempus. Duis in dictum urna.

Aliquam nibh mi, faucibus et sem nec, venenatis finibus leo. Curabitur feugiat felis at mauris bibendum, vehicula imperdiet elit sagittis. Ut feugiat gravida turpis, at euismod sapien imperdiet vitae. Sed mattis tortor eget consectetur maximus. Sed ultricies, purus eu eleifend bibendum, justo elit tristique mauris, quis mattis sem magna ut neque. Morbi euismod velit nec justo tempor lacinia. Vivamus faucibus nibh ac porttitor dapibus.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce rhoncus ipsum quis leo mattis pharetra. Nunc posuere, libero et auctor aliquet, risus ligula sagittis libero, sed molestie ligula tellus id mi. Praesent feugiat interdum enim, quis laoreet metus placerat eget. In sit amet tempor nunc. Maecenas id massa gravida, porta tellus in, sodales libero. Sed id auctor lectus. Morbi lorem dui, eleifend id tellus et, blandit lobortis quam. Sed convallis tellus sed eros elementum, rhoncus tincidunt sapien vulputate. In porta molestie varius. In a lorem a nulla vehicula tempor. Sed scelerisque volutpat ante, in venenatis lectus aliquam cursus. In dictum ac arcu id feugiat. Phasellus quis eros a leo blandit ultricies. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas aliquam libero nec est sagittis ullamcorper.

Mauris blandit vehicula lorem at elementum. Nam sollicitudin eu lacus ut luctus. Quisque sed auctor risus, auctor condimentum libero. Pellentesque at efficitur eros. Proin lacinia, lacus ac porttitor suscipit, augue justo rutrum tellus, ut vehicula tortor ex iaculis diam. Duis id hendrerit ex. Ut et diam a lorem eleifend lacinia sit amet vitae odio. Pellentesque non molestie felis. Aliquam ac ornare turpis, vehicula facilisis lectus. Quisque dolor ipsum, placerat non lobortis in, varius non massa. Sed maximus euismod neque. Donec consequat, risus nec dapibus vulputate, tellus magna ultricies metus, non pulvinar justo lorem sit amet nisi. Suspendisse sollicitudin ex lectus, vitae varius quam condimentum ac. Praesent vehicula est sed dui tempus ornare. Integer egestas malesuada placerat.

Integer interdum leo sit amet eros maximus, eu consequat diam lobortis. Cras varius est et cursus viverra. Nunc aliquet fermentum libero, malesuada accumsan augue consequat id. Donec consectetur tortor id lectus gravida mattis. Nam ut dolor vitae leo tristique tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus orci in velit molestie sollicitudin. Morbi suscipit sem non fermentum malesuada. Nullam ac nisi sodales, ultrices dolor in, lacinia orci. Nam nisi lacus, suscipit sit amet varius vel, pretium et massa. Sed id massa sed ligula mollis tristique sed ac magna. Sed egestas, magna non semper ornare, velit nulla porttitor arcu, eget tempor est tortor quis lectus. Aenean dignissim in diam sed facilisis.

Integer nec risus elit. Duis tempus nunc odio, id tempor velit consectetur at. Pellentesque sed posuere metus, sit amet tincidunt felis. Maecenas vehicula viverra ipsum. Nunc arcu urna, feugiat et mattis ornare, molestie in quam. Fusce ac consequat nibh. Morbi porttitor non ligula sagittis vestibulum. Pellentesque egestas, dui ut finibus maximus, lectus neque fringilla ante, vitae laoreet nisl massa eget nisi. Cras egestas ipsum in massa mollis, sit amet suscipit velit sodales. In porttitor lectus et dui malesuada consectetur. Praesent lobortis odio eu mauris maximus iaculis. Quisque aliquet dolor id eleifend fermentum. Nullam finibus metus sagittis auctor hendrerit. Pellentesque vel erat eget nulla vehicula tempus. Duis in dictum urna.

Aliquam nibh mi, faucibus et sem nec, venenatis finibus leo. Curabitur feugiat felis at mauris bibendum, vehicula imperdiet elit sagittis. Ut feugiat gravida turpis, at euismod sapien imperdiet vitae. Sed mattis tortor eget consectetur maximus. Sed ultricies, purus eu eleifend bibendum, justo elit tristique mauris, quis mattis sem magna ut neque. Morbi euismod velit nec justo tempor lacinia. Vivamus faucibus nibh ac porttitor dapibus.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce rhoncus ipsum quis leo mattis pharetra. Nunc posuere, libero et auctor aliquet, risus ligula sagittis libero, sed molestie ligula tellus id mi. Praesent feugiat interdum enim, quis laoreet metus placerat eget. In sit amet tempor nunc. Maecenas id massa gravida, porta tellus in, sodales libero. Sed id auctor lectus. Morbi lorem dui, eleifend id tellus et, blandit lobortis quam. Sed convallis tellus sed eros elementum, rhoncus tincidunt sapien vulputate. In porta molestie varius. In a lorem a nulla vehicula tempor. Sed scelerisque volutpat ante, in venenatis lectus aliquam cursus. In dictum ac arcu id feugiat. Phasellus quis eros a leo blandit ultricies. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas aliquam libero nec est sagittis ullamcorper.

Mauris blandit vehicula lorem at elementum. Nam sollicitudin eu lacus ut luctus. Quisque sed auctor risus, auctor condimentum libero. Pellentesque at efficitur eros. Proin lacinia, lacus ac porttitor suscipit, augue justo rutrum tellus, ut vehicula tortor ex iaculis diam. Duis id hendrerit ex. Ut et diam a lorem eleifend lacinia sit amet vitae odio. Pellentesque non molestie felis. Aliquam ac ornare turpis, vehicula facilisis lectus. Quisque dolor ipsum, placerat non lobortis in, varius non massa. Sed maximus euismod neque. Donec consequat, risus nec dapibus vulputate, tellus magna ultricies metus, non pulvinar justo lorem sit amet nisi. Suspendisse sollicitudin ex lectus, vitae varius quam condimentum ac. Praesent vehicula est sed dui tempus ornare. Integer egestas malesuada placerat.

Integer interdum leo sit amet eros maximus, eu consequat diam lobortis. Cras varius est et cursus viverra. Nunc aliquet fermentum libero, malesuada accumsan augue consequat id. Donec consectetur tortor id lectus gravida mattis. Nam ut dolor vitae leo tristique tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus orci in velit molestie sollicitudin. Morbi suscipit sem non fermentum malesuada. Nullam ac nisi sodales, ultrices dolor in, lacinia orci. Nam nisi lacus, suscipit sit amet varius vel, pretium et massa. Sed id massa sed ligula mollis tristique sed ac magna. Sed egestas, magna non semper ornare, velit nulla porttitor arcu, eget tempor est tortor quis lectus. Aenean dignissim in diam sed facilisis.

Integer nec risus elit. Duis tempus nunc odio, id tempor velit consectetur at. Pellentesque sed posuere metus, sit amet tincidunt felis. Maecenas vehicula viverra ipsum. Nunc arcu urna, feugiat et mattis ornare, molestie in quam. Fusce ac consequat nibh. Morbi porttitor non ligula sagittis vestibulum. Pellentesque egestas, dui ut finibus maximus, lectus neque fringilla ante, vitae laoreet nisl massa eget nisi. Cras egestas ipsum in massa mollis, sit amet suscipit velit sodales. In porttitor lectus et dui malesuada consectetur. Praesent lobortis odio eu mauris maximus iaculis. Quisque aliquet dolor id eleifend fermentum. Nullam finibus metus sagittis auctor hendrerit. Pellentesque vel erat eget nulla vehicula tempus. Duis in dictum urna.

Aliquam nibh mi, faucibus et sem nec, venenatis finibus leo. Curabitur feugiat felis at mauris bibendum, vehicula imperdiet elit sagittis. Ut feugiat gravida turpis, at euismod sapien imperdiet vitae. Sed mattis tortor eget consectetur maximus. Sed ultricies, purus eu eleifend bibendum, justo elit tristique mauris, quis mattis sem magna ut neque. Morbi euismod velit nec justo tempor lacinia. Vivamus faucibus nibh ac porttitor dapibus.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce rhoncus ipsum quis leo mattis pharetra. Nunc posuere, libero et auctor aliquet, risus ligula sagittis libero, sed molestie ligula tellus id mi. Praesent feugiat interdum enim, quis laoreet metus placerat eget. In sit amet tempor nunc. Maecenas id massa gravida, porta tellus in, sodales libero. Sed id auctor lectus. Morbi lorem dui, eleifend id tellus et, blandit lobortis quam. Sed convallis tellus sed eros elementum, rhoncus tincidunt sapien vulputate. In porta molestie varius. In a lorem a nulla vehicula tempor. Sed scelerisque volutpat ante, in venenatis lectus aliquam cursus. In dictum ac arcu id feugiat. Phasellus quis eros a leo blandit ultricies. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas aliquam libero nec est sagittis ullamcorper.

Mauris blandit vehicula lorem at elementum. Nam sollicitudin eu lacus ut luctus. Quisque sed auctor risus, auctor condimentum libero. Pellentesque at efficitur eros. Proin lacinia, lacus ac porttitor suscipit, augue justo rutrum tellus, ut vehicula tortor ex iaculis diam. Duis id hendrerit ex. Ut et diam a lorem eleifend lacinia sit amet vitae odio. Pellentesque non molestie felis. Aliquam ac ornare turpis, vehicula facilisis lectus. Quisque dolor ipsum, placerat non lobortis in, varius non massa. Sed maximus euismod neque. Donec consequat, risus nec dapibus vulputate, tellus magna ultricies metus, non pulvinar justo lorem sit amet nisi. Suspendisse sollicitudin ex lectus, vitae varius quam condimentum ac. Praesent vehicula est sed dui tempus ornare. Integer egestas malesuada placerat.

Integer interdum leo sit amet eros maximus, eu consequat diam lobortis. Cras varius est et cursus viverra. Nunc aliquet fermentum libero, malesuada accumsan augue consequat id. Donec consectetur tortor id lectus gravida mattis. Nam ut dolor vitae leo tristique tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus orci in velit molestie sollicitudin. Morbi suscipit sem non fermentum malesuada. Nullam ac nisi sodales, ultrices dolor in, lacinia orci. Nam nisi lacus, suscipit sit amet varius vel, pretium et massa. Sed id massa sed ligula mollis tristique sed ac magna. Sed egestas, magna non semper ornare, velit nulla porttitor arcu, eget tempor est tortor quis lectus. Aenean dignissim in diam sed facilisis.

Integer nec risus elit. Duis tempus nunc odio, id tempor velit consectetur at. Pellentesque sed posuere metus, sit amet tincidunt felis. Maecenas vehicula viverra ipsum. Nunc arcu urna, feugiat et mattis ornare, molestie in quam. Fusce ac consequat nibh. Morbi porttitor non ligula sagittis vestibulum. Pellentesque egestas, dui ut finibus maximus, lectus neque fringilla ante, vitae laoreet nisl massa eget nisi. Cras egestas ipsum in massa mollis, sit amet suscipit velit sodales. In porttitor lectus et dui malesuada consectetur. Praesent lobortis odio eu mauris maximus iaculis. Quisque aliquet dolor id eleifend fermentum. Nullam finibus metus sagittis auctor hendrerit. Pellentesque vel erat eget nulla vehicula tempus. Duis in dictum urna.

Aliquam nibh mi, faucibus et sem nec, venenatis finibus leo. Curabitur feugiat felis at mauris bibendum, vehicula imperdiet elit sagittis. Ut feugiat gravida turpis, at euismod sapien imperdiet vitae. Sed mattis tortor eget consectetur maximus. Sed ultricies, purus eu eleifend bibendum, justo elit tristique mauris, quis mattis sem magna ut neque. Morbi euismod velit nec justo tempor lacinia. Vivamus faucibus nibh ac porttitor dapibus.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce rhoncus ipsum quis leo mattis pharetra. Nunc posuere, libero et auctor aliquet, risus ligula sagittis libero, sed molestie ligula tellus id mi. Praesent feugiat interdum enim, quis laoreet metus placerat eget. In sit amet tempor nunc. Maecenas id massa gravida, porta tellus in, sodales libero. Sed id auctor lectus. Morbi lorem dui, eleifend id tellus et, blandit lobortis quam. Sed convallis tellus sed eros elementum, rhoncus tincidunt sapien vulputate. In porta molestie varius. In a lorem a nulla vehicula tempor. Sed scelerisque volutpat ante, in venenatis lectus aliquam cursus. In dictum ac arcu id feugiat. Phasellus quis eros a leo blandit ultricies. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas aliquam libero nec est sagittis ullamcorper.

Mauris blandit vehicula lorem at elementum. Nam sollicitudin eu lacus ut luctus. Quisque sed auctor risus, auctor condimentum libero. Pellentesque at efficitur eros. Proin lacinia, lacus ac porttitor suscipit, augue justo rutrum tellus, ut vehicula tortor ex iaculis diam. Duis id hendrerit ex. Ut et diam a lorem eleifend lacinia sit amet vitae odio. Pellentesque non molestie felis. Aliquam ac ornare turpis, vehicula facilisis lectus. Quisque dolor ipsum, placerat non lobortis in, varius non massa. Sed maximus euismod neque. Donec consequat, risus nec dapibus vulputate, tellus magna ultricies metus, non pulvinar justo lorem sit amet nisi. Suspendisse sollicitudin ex lectus, vitae varius quam condimentum ac. Praesent vehicula est sed dui tempus ornare. Integer egestas malesuada placerat.

Integer interdum leo sit amet eros maximus, eu consequat diam lobortis. Cras varius est et cursus viverra. Nunc aliquet fermentum libero, malesuada accumsan augue consequat id. Donec consectetur tortor id lectus gravida mattis. Nam ut dolor vitae leo tristique tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus orci in velit molestie sollicitudin. Morbi suscipit sem non fermentum malesuada. Nullam ac nisi sodales, ultrices dolor in, lacinia orci. Nam nisi lacus, suscipit sit amet varius vel, pretium et massa. Sed id massa sed ligula mollis tristique sed ac magna. Sed egestas, magna non semper ornare, velit nulla porttitor arcu, eget tempor est tortor quis lectus. Aenean dignissim in diam sed facilisis.

Integer nec risus elit. Duis tempus nunc odio, id tempor velit consectetur at. Pellentesque sed posuere metus, sit amet tincidunt felis. Maecenas vehicula viverra ipsum. Nunc arcu urna, feugiat et mattis ornare, molestie in quam. Fusce ac consequat nibh. Morbi porttitor non ligula sagittis vestibulum. Pellentesque egestas, dui ut finibus maximus, lectus neque fringilla ante, vitae laoreet nisl massa eget nisi. Cras egestas ipsum in massa mollis, sit amet suscipit velit sodales. In porttitor lectus et dui malesuada consectetur. Praesent lobortis odio eu mauris maximus iaculis. Quisque aliquet dolor id eleifend fermentum. Nullam finibus metus sagittis auctor hendrerit. Pellentesque vel erat eget nulla vehicula tempus. Duis in dictum urna.

Aliquam nibh mi, faucibus et sem nec, venenatis finibus leo. Curabitur feugiat felis at mauris bibendum, vehicula imperdiet elit sagittis. Ut feugiat gravida turpis, at euismod sapien imperdiet vitae. Sed mattis tortor eget consectetur maximus. Sed ultricies, purus eu eleifend bibendum, justo elit tristique mauris, quis mattis sem magna ut neque. Morbi euismod velit nec justo tempor lacinia. Vivamus faucibus nibh ac porttitor dapibus.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce rhoncus ipsum quis leo mattis pharetra. Nunc posuere, libero et auctor aliquet, risus ligula sagittis libero, sed molestie ligula tellus id mi. Praesent feugiat interdum enim, quis laoreet metus placerat eget. In sit amet tempor nunc. Maecenas id massa gravida, porta tellus in, sodales libero. Sed id auctor lectus. Morbi lorem dui, eleifend id tellus et, blandit lobortis quam. Sed convallis tellus sed eros elementum, rhoncus tincidunt sapien vulputate. In porta molestie varius. In a lorem a nulla vehicula tempor. Sed scelerisque volutpat ante, in venenatis lectus aliquam cursus. In dictum ac arcu id feugiat. Phasellus quis eros a leo blandit ultricies. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas aliquam libero nec est sagittis ullamcorper.

Mauris blandit vehicula lorem at elementum. Nam sollicitudin eu lacus ut luctus. Quisque sed auctor risus, auctor condimentum libero. Pellentesque at efficitur eros. Proin lacinia, lacus ac porttitor suscipit, augue justo rutrum tellus, ut vehicula tortor ex iaculis diam. Duis id hendrerit ex. Ut et diam a lorem eleifend lacinia sit amet vitae odio. Pellentesque non molestie felis. Aliquam ac ornare turpis, vehicula facilisis lectus. Quisque dolor ipsum, placerat non lobortis in, varius non massa. Sed maximus euismod neque. Donec consequat, risus nec dapibus vulputate, tellus magna ultricies metus, non pulvinar justo lorem sit amet nisi. Suspendisse sollicitudin ex lectus, vitae varius quam condimentum ac. Praesent vehicula est sed dui tempus ornare. Integer egestas malesuada placerat.

Integer interdum leo sit amet eros maximus, eu consequat diam lobortis. Cras varius est et cursus viverra. Nunc aliquet fermentum libero, malesuada accumsan augue consequat id. Donec consectetur tortor id lectus gravida mattis. Nam ut dolor vitae leo tristique tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus orci in velit molestie sollicitudin. Morbi suscipit sem non fermentum malesuada. Nullam ac nisi sodales, ultrices dolor in, lacinia orci. Nam nisi lacus, suscipit sit amet varius vel, pretium et massa. Sed id massa sed ligula mollis tristique sed ac magna. Sed egestas, magna non semper ornare, velit nulla porttitor arcu, eget tempor est tortor quis lectus. Aenean dignissim in diam sed facilisis.

Integer nec risus elit. Duis tempus nunc odio, id tempor velit consectetur at. Pellentesque sed posuere metus, sit amet tincidunt felis. Maecenas vehicula viverra ipsum. Nunc arcu urna, feugiat et mattis ornare, molestie in quam. Fusce ac consequat nibh. Morbi porttitor non ligula sagittis vestibulum. Pellentesque egestas, dui ut finibus maximus, lectus neque fringilla ante, vitae laoreet nisl massa eget nisi. Cras egestas ipsum in massa mollis, sit amet suscipit velit sodales. In porttitor lectus et dui malesuada consectetur. Praesent lobortis odio eu mauris maximus iaculis. Quisque aliquet dolor id eleifend fermentum. Nullam finibus metus sagittis auctor hendrerit. Pellentesque vel erat eget nulla vehicula tempus. Duis in dictum urna.

Aliquam nibh mi, faucibus et sem nec, venenatis finibus leo. Curabitur feugiat felis at mauris bibendum, vehicula imperdiet elit sagittis. Ut feugiat gravida turpis, at euismod sapien imperdiet vitae. Sed mattis tortor eget consectetur maximus. Sed ultricies, purus eu eleifend bibendum, justo elit tristique mauris, quis mattis sem magna ut neque. Morbi euismod velit nec justo tempor lacinia. Vivamus faucibus nibh ac porttitor dapibus.
</p>
    <p>This means that you can create and write <em>.ts/.tsx</em> files for your pages, components etc. Please note that the <em>gatsby-*.js</em> files (like gatsby-node.js) currently don't support TypeScript yet.</p>
    <p>For type checking you'll want to install <em>typescript</em> via npm and run <em>tsc --init</em> to create a <em>.tsconfig</em> file.</p>
    <p>You're currently on the page "{path}" which was built on {data.site.buildTime}.</p>
    <p>To learn more, head over to our <a href="https://www.gatsbyjs.com/docs/typescript/">documentation about TypeScript</a>.</p>
    <Link to="/">Go back to the homepage</Link>
  </Layout>
)

export default UsingTypescript

export const query = graphql`
  {
    site {
      buildTime(formatString: "YYYY-MM-DD hh:mm a z")
    }
  }
`
